### ISSUE TITLE
[docs] Add Scala client documentation for Pulsar

### ISSUE THREAD

**Issue by Jennifer88huang** [streamnative/pulsar#1921]
See http://pulsar.apache.org/docs/en/client-libraries/
Links are added, yet the detailed content is not added. Add similar content with that for other clients (e.g.: Java, Python...)

**Comment by Anonymitaet** [comment]
Confirmed w/ @codelipenghu, I need to ask the author if he'd like to donate the project to Pulsar, if yes, then I will work on the docs. Otherwise, the priority of this task is low.

Since the author's email cannot be found and a direct tweet msg cannot be sent to him, I've [opened an issue in his Scala repo](https://github.com/sksamuel/pulsar4s/issues/261). Waiting for his feedback.

**Comment by Anonymitaet** [comment]
![image.png](https://images.zenhubusercontent.com/5fd87a84b9bf7aad279b0809/0105f960-d1c4-402f-a8b4-86363a64ed22)

**Comment by Anonymitaet** [comment]
Same to Haskell

![image.png](https://images.zenhubusercontent.com/5fd87a84b9bf7aad279b0809/610fa13d-c6ff-4030-b8bb-0c17bbdc2883)

![image.png](https://images.zenhubusercontent.com/5fd87a84b9bf7aad279b0809/eb904136-a7cb-40ba-9132-55988e364aba)
